---
- name: Install and start MongoDB
  hosts: all
  become: true

  tasks:
    - name: Install apt-transport-https
      apt:
        name: apt-transport-https
        state: present

    - name: add pgp-key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: EA312927

    - name: add MongoDB repository
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse
        state: present

    - name: install mongod
      apt:
        name: mongodb-org
        state: present
        update_cache: yes
        allow_unauthenticated: yes

    - name: enable mongod
      systemd:
        name: mongod
        enabled: yes
